feat: adding fairea tool
holistic-ai/holisticai pull request #88
Opened 2023-10-07 01:43 UTC by fracarfer5

adding fairness accuracy trade-off tool, implemented main class, tutorial and test units

2023-10-24 13:16 UTC, crismunoz requested changes

2023-10-24 13:16 UTC, crismunoz commented on holisticai/utils/trade_off_analysers/fairea.py
> +    def __init__(
- Follow Bias Mitigator format.
- Reference (URL)
- explain acc_metric (used for what?)

2023-10-24 13:16 UTC, crismunoz commented on holisticai/utils/trade_off_analysers/fairea.py
> +    def create_baseline(self, x, y, group_a, group_b):
Use this format:
fairea.create_baseline(X_train, y_train, group_a_tr, group_b_tr, num_splits=10, test_size=0.2)

2023-10-24 13:16 UTC, crismunoz commented on tutorials/trade_off/fairea_tutorial.ipynb
explain : plot_baseline
use figsize instead of size
# Fill area good-trade of and bad trade-off
fairea.region_classification() # trade_off_region_classification
fairea.determine_area() # trade_off_region_area
fairea.get_best() # get_best_model

2023-10-24 13:16 UTC, crismunoz commented on holisticai/utils/trade_off_analysers/fairea.py
> +    Fairea class for calculating the trade-off between accuracy and fairness of a classification model.
only binary?

2023-10-24 13:28 UTC, crismunoz requested changes
great

2023-10-24 13:28 UTC, crismunoz commented on holisticai/utils/trade_off_analysers/fairea.py
> +        if acc_metric == "acc":
```python
metrics = { 
  "acc": accuracy_score,
  "auc":  roc_auc_score,
  "sp": statistical_parity,
  "aod": average_odds_diff
}

self.acc_fn = metrics [acc_metric]
```

2023-10-24 13:28 UTC, crismunoz commented on holisticai/utils/trade_off_analysers/fairea.py
> +            self.baseline_acc.reshape(-1, 1)
reshape(-1,1) inside __create_baseline

2023-10-24 13:28 UTC, crismunoz commented on holisticai/utils/trade_off_analysers/utils_fairea.py
> +    """
return?

2023-10-25 14:45 UTC, fracarfer5 commented on holisticai/utils/trade_off_analysers/fairea.py
> +    def __init__(
done

2023-10-25 14:46 UTC, fracarfer5 commented on holisticai/utils/trade_off_analysers/fairea.py
> +        if acc_metric == "acc":
changed

2023-10-25 14:46 UTC, fracarfer5 commented on holisticai/utils/trade_off_analysers/utils_fairea.py
> +    """
done

2023-10-25 14:46 UTC, fracarfer5 commented on holisticai/utils/trade_off_analysers/fairea.py
> +            self.baseline_acc.reshape(-1, 1)
done

2023-10-25 14:46 UTC, fracarfer5 commented on holisticai/utils/trade_off_analysers/fairea.py
> +    def create_baseline(self, x, y, group_a, group_b):
done

2023-10-26 02:11 UTC, crismunoz approved these changes

2023-10-26 02:11 UTC, merged